version: '3.8'

services:
  bot:
    build:
      context: .
    environment:
      - DEBUG=true
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_AI_KEY=${OPENAI_AI_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: sleep infinity
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: armenia_outages
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d armenia_outages"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
