"""add sent field to agg table

Revision ID: 051b156c09fa
Revises: 079e0290600f
Create Date: 2024-08-09 19:09:50.915937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051b156c09fa'
down_revision: Union[str, None] = '079e0290600f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent', sa.Boolean(), nullable=True))
        batch_op.alter_column('district',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('house_numbers',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_events', schema=None) as batch_op:
        batch_op.alter_column('house_numbers',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('district',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('sent')

    # ### end Alembic commands ###
