"""Add AggregatedEvent table

Revision ID: 079e0290600f
Revises: 2b8360fec3ec
Create Date: 2024-08-09 19:01:16.413850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079e0290600f'
down_revision: Union[str, None] = '2b8360fec3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('house_numbers', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('RU', 'EN', 'AM', name='language'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_time', 'area', 'district', 'language', name='_unique_agg_event')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aggregated_events')
    # ### end Alembic commands ###
