"""add cascade deleting

Revision ID: 2de134b10f42
Revises: 35fbc3613ec1
Create Date: 2024-10-04 17:32:01.430543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de134b10f42'
down_revision: Union[str, None] = '35fbc3613ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_event_association_event_id_fkey', 'post_event_association', type_='foreignkey')
    op.drop_constraint('post_event_association_post_id_fkey', 'post_event_association', type_='foreignkey')
    op.create_foreign_key(None, 'post_event_association', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_event_association', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_event_association', type_='foreignkey')
    op.drop_constraint(None, 'post_event_association', type_='foreignkey')
    op.create_foreign_key('post_event_association_post_id_fkey', 'post_event_association', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('post_event_association_event_id_fkey', 'post_event_association', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
