"""Add unique constraint to subscriptions

Revision ID: 31d0052f2767
Revises: c67b9c04ebcd
Create Date: 2024-08-24 18:24:28.714479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31d0052f2767"
down_revision: Union[str, None] = "c67b9c04ebcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_areas_name", ["name"])

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "_user_area_keyword_uc", ["user_id", "area_id", "keyword"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_constraint("_user_area_keyword_uc", type_="unique")

    with op.batch_alter_table("areas", schema=None) as batch_op:
        batch_op.drop_constraint("uq_areas_name", type_="unique")

    # ### end Alembic commands ###
