"""create Notification

Revision ID: 35fbc3613ec1
Revises: ffc18e1a5dd6
Create Date: 2024-09-04 15:32:13.486659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "35fbc3613ec1"
down_revision: Union[str, None] = "ffc18e1a5dd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    post_type_enum = postgresql.ENUM(
        "EMERGENCY_POWER",
        "EMERGENCY_WATER",
        "EMERGENCY_GAS",
        "SCHEDULED_POWER",
        "SCHEDULED_WATER",
        "SCHEDULED_GAS",
        name="posttype",
        create_type=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column(
            "language",
            postgresql.ENUM("RU", "EN", "HY", name="language", create_type=False),
            nullable=False,
        ),
        sa.Column("notification_type", post_type_enum, nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("creation_time", sa.DateTime(), nullable=True),
        sa.Column("sent_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("posts", "post_type", existing_type=post_type_enum, nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    post_type_enum = postgresql.ENUM(
        "EMERGENCY_POWER",
        "EMERGENCY_WATER",
        "EMERGENCY_GAS",
        "SCHEDULED_POWER",
        "SCHEDULED_WATER",
        "SCHEDULED_GAS",
        name="posttype",
        create_type=False,
    )
    op.alter_column("posts", "post_type", existing_type=post_type_enum, nullable=True)
    op.drop_table("notifications")
    # ### end Alembic commands ###
