"""rework model fields

Revision ID: 4150d14ee39f
Revises: a91d6d0d6809
Create Date: 2024-08-10 21:30:42.236615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4150d14ee39f'
down_revision: Union[str, None] = 'a91d6d0d6809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('planned',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('date')

    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sent_time', sa.String(), nullable=True))
        batch_op.alter_column('house_numbers',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('house_numbers',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('sent_time')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('text')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('planned',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
