"""Add text field to Event model

Revision ID: 4421cdd56c6a
Revises: a2b549e44ea3
Create Date: 2024-08-04 15:08:06.194527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4421cdd56c6a'
down_revision: Union[str, None] = 'a2b549e44ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
