"""remove language field from Subscription model

Revision ID: 9201c26ccb5d
Revises: a71638eb69ac
Create Date: 2024-08-24 12:07:22.876136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9201c26ccb5d'
down_revision: Union[str, None] = 'a71638eb69ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=2), nullable=True))

    # ### end Alembic commands ###
