"""change Language field for Post

Revision ID: 92d4b503dd42
Revises: 7fe2f09a28b5
Create Date: 2024-08-23 10:02:53.300403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d4b503dd42'
down_revision: Union[str, None] = '7fe2f09a28b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
