"""remove house_numbers field

Revision ID: 9696942d389a
Revises: ebca3b9dc183
Create Date: 2024-08-02 11:24:11.769576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9696942d389a"
down_revision: Union[str, None] = "ebca3b9dc183"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("house_numbers")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("house_numbers", sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
