"""remove ProcessedEvent

Revision ID: a71638eb69ac
Revises: 92d4b503dd42
Create Date: 2024-08-24 09:25:32.902486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71638eb69ac'
down_revision: Union[str, None] = '92d4b503dd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.VARCHAR(), nullable=True),
    sa.Column('area', sa.VARCHAR(), nullable=True),
    sa.Column('district', sa.VARCHAR(), nullable=True),
    sa.Column('house_numbers', sa.TEXT(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=2), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('sent', sa.BOOLEAN(), nullable=True),
    sa.Column('planned', sa.BOOLEAN(), nullable=True),
    sa.Column('end_time', sa.VARCHAR(), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.VARCHAR(), nullable=True),
    sa.Column('sent_time', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_time', 'area', 'district', 'event_type', 'language', name='_unique_agg_event')
    )
    # ### end Alembic commands ###
