"""add end time field to processed events table

Revision ID: a91d6d0d6809
Revises: 56258b59e590
Create Date: 2024-08-10 21:15:06.861530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91d6d0d6809'
down_revision: Union[str, None] = '56258b59e590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
