"""create posts table

Revision ID: c624434d32c9
Revises: 5c08cb2c4485
Create Date: 2024-08-22 19:58:44.565371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c624434d32c9'
down_revision: Union[str, None] = '5c08cb2c4485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('posted_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_event_association',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'event_id')
    )
    op.drop_table('last_page')
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_agg_event', type_='unique')
        batch_op.create_unique_constraint('_unique_agg_event', ['start_time', 'area', 'district', 'event_type', 'language'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_agg_event', type_='unique')
        batch_op.create_unique_constraint('_unique_agg_event', ['start_time', 'area', 'district', 'language'])

    op.create_table('last_page',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('page_number', sa.INTEGER(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=2), nullable=True),
    sa.Column('planned', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post_event_association')
    op.drop_table('posts')
    # ### end Alembic commands ###
