"""change posts

Revision ID: e754d72da764
Revises: b43c49dd73be
Create Date: 2024-09-01 13:01:44.533955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e754d72da764'
down_revision: Union[str, None] = 'b43c49dd73be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bot_users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot_users', type_='unique')
    # ### end Alembic commands ###
