"""add hash column to events

Revision ID: ebca3b9dc183
Revises: 
Create Date: 2024-08-02 11:13:50.661538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebca3b9dc183"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hash", sa.String(), nullable=True))
        batch_op.create_unique_constraint("_event_hash_uc", ["hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint("_event_hash_uc", type_="unique")
        batch_op.drop_column("hash")
    # ### end Alembic commands ###
